//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMaxDataServiceExample.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SIDValue", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class SIDValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SID {
            get {
                return this.SIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SIDField, value) != true)) {
                    this.SIDField = value;
                    this.RaisePropertyChanged("SID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Since {
            get {
                return this.SinceField;
            }
            set {
                if ((this.SinceField.Equals(value) != true)) {
                    this.SinceField = value;
                    this.RaisePropertyChanged("Since");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBulkParams", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class GetBulkParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SID {
            get {
                return this.SIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SIDField, value) != true)) {
                    this.SIDField = value;
                    this.RaisePropertyChanged("SID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkWrapper", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.DataService.Bulk bulkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.DataService.Bulk bulk {
            get {
                return this.bulkField;
            }
            set {
                if ((object.ReferenceEquals(this.bulkField, value) != true)) {
                    this.bulkField = value;
                    this.RaisePropertyChanged("bulk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bulk", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.DataService.BulkToolChangeInfoTypeBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.DataService.BulkNotificationDataTypeBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.DataService.BulkRemoteCommandDataTypeBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.DataService.BulkMachinePosTypeBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.DataService.BulkToolDataTypeBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.DataService.BulkPartSetupTypeBox))]
    public partial class Bulk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkToolChangeInfoTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkToolChangeInfoTypeBox : WinMaxDataServiceExample.DataService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkToolChangeInfoType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkToolChangeInfoType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkNotificationDataTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkNotificationDataTypeBox : WinMaxDataServiceExample.DataService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkNotificationDataType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkNotificationDataType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkRemoteCommandDataTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkRemoteCommandDataTypeBox : WinMaxDataServiceExample.DataService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.DataService.UnmanagedDataTypesRemoteCommandInfoType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.DataService.UnmanagedDataTypesRemoteCommandInfoType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkMachinePosTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkMachinePosTypeBox : WinMaxDataServiceExample.DataService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkMachinePosType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkMachinePosType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkToolDataTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkToolDataTypeBox : WinMaxDataServiceExample.DataService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkToolDataType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkToolDataType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkPartSetupTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkPartSetupTypeBox : WinMaxDataServiceExample.DataService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkCurrentPartSetupType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkCurrentPartSetupType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.BulkToolChangeInfoType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesBulkToolChangeInfoType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bAutoSafetyCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bAutoToolChangeCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bManualSafetyCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bManualToolChangeCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bMoveToZone1CouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bMoveToZone2CouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bPalletChangeCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bTPSInsertToolCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bTPSRemoveToolCouldMoveField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bAutoSafetyCouldMove {
            get {
                return this.bAutoSafetyCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bAutoSafetyCouldMoveField, value) != true)) {
                    this.bAutoSafetyCouldMoveField = value;
                    this.RaisePropertyChanged("bAutoSafetyCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bAutoToolChangeCouldMove {
            get {
                return this.bAutoToolChangeCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bAutoToolChangeCouldMoveField, value) != true)) {
                    this.bAutoToolChangeCouldMoveField = value;
                    this.RaisePropertyChanged("bAutoToolChangeCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bManualSafetyCouldMove {
            get {
                return this.bManualSafetyCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bManualSafetyCouldMoveField, value) != true)) {
                    this.bManualSafetyCouldMoveField = value;
                    this.RaisePropertyChanged("bManualSafetyCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bManualToolChangeCouldMove {
            get {
                return this.bManualToolChangeCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bManualToolChangeCouldMoveField, value) != true)) {
                    this.bManualToolChangeCouldMoveField = value;
                    this.RaisePropertyChanged("bManualToolChangeCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bMoveToZone1CouldMove {
            get {
                return this.bMoveToZone1CouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bMoveToZone1CouldMoveField, value) != true)) {
                    this.bMoveToZone1CouldMoveField = value;
                    this.RaisePropertyChanged("bMoveToZone1CouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bMoveToZone2CouldMove {
            get {
                return this.bMoveToZone2CouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bMoveToZone2CouldMoveField, value) != true)) {
                    this.bMoveToZone2CouldMoveField = value;
                    this.RaisePropertyChanged("bMoveToZone2CouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bPalletChangeCouldMove {
            get {
                return this.bPalletChangeCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bPalletChangeCouldMoveField, value) != true)) {
                    this.bPalletChangeCouldMoveField = value;
                    this.RaisePropertyChanged("bPalletChangeCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bTPSInsertToolCouldMove {
            get {
                return this.bTPSInsertToolCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bTPSInsertToolCouldMoveField, value) != true)) {
                    this.bTPSInsertToolCouldMoveField = value;
                    this.RaisePropertyChanged("bTPSInsertToolCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bTPSRemoveToolCouldMove {
            get {
                return this.bTPSRemoveToolCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bTPSRemoveToolCouldMoveField, value) != true)) {
                    this.bTPSRemoveToolCouldMoveField = value;
                    this.RaisePropertyChanged("bTPSRemoveToolCouldMove");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.BulkNotificationDataType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesBulkNotificationDataType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] m_MsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int m_MsgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort m_NotificationIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.DataService.UnmanagedDataTypes_SYSTEMTIME m_TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] m_wrcFileNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] m_Msg {
            get {
                return this.m_MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.m_MsgField, value) != true)) {
                    this.m_MsgField = value;
                    this.RaisePropertyChanged("m_Msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int m_MsgType {
            get {
                return this.m_MsgTypeField;
            }
            set {
                if ((this.m_MsgTypeField.Equals(value) != true)) {
                    this.m_MsgTypeField = value;
                    this.RaisePropertyChanged("m_MsgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort m_NotificationIndex {
            get {
                return this.m_NotificationIndexField;
            }
            set {
                if ((this.m_NotificationIndexField.Equals(value) != true)) {
                    this.m_NotificationIndexField = value;
                    this.RaisePropertyChanged("m_NotificationIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.DataService.UnmanagedDataTypes_SYSTEMTIME m_Timestamp {
            get {
                return this.m_TimestampField;
            }
            set {
                if ((this.m_TimestampField.Equals(value) != true)) {
                    this.m_TimestampField = value;
                    this.RaisePropertyChanged("m_Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] m_wrcFileName {
            get {
                return this.m_wrcFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.m_wrcFileNameField, value) != true)) {
                    this.m_wrcFileNameField = value;
                    this.RaisePropertyChanged("m_wrcFileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes._SYSTEMTIME", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypes_SYSTEMTIME : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wDayOfWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wMillisecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wMinuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wSecondField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wYearField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wDay {
            get {
                return this.wDayField;
            }
            set {
                if ((this.wDayField.Equals(value) != true)) {
                    this.wDayField = value;
                    this.RaisePropertyChanged("wDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wDayOfWeek {
            get {
                return this.wDayOfWeekField;
            }
            set {
                if ((this.wDayOfWeekField.Equals(value) != true)) {
                    this.wDayOfWeekField = value;
                    this.RaisePropertyChanged("wDayOfWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wHour {
            get {
                return this.wHourField;
            }
            set {
                if ((this.wHourField.Equals(value) != true)) {
                    this.wHourField = value;
                    this.RaisePropertyChanged("wHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wMilliseconds {
            get {
                return this.wMillisecondsField;
            }
            set {
                if ((this.wMillisecondsField.Equals(value) != true)) {
                    this.wMillisecondsField = value;
                    this.RaisePropertyChanged("wMilliseconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wMinute {
            get {
                return this.wMinuteField;
            }
            set {
                if ((this.wMinuteField.Equals(value) != true)) {
                    this.wMinuteField = value;
                    this.RaisePropertyChanged("wMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wMonth {
            get {
                return this.wMonthField;
            }
            set {
                if ((this.wMonthField.Equals(value) != true)) {
                    this.wMonthField = value;
                    this.RaisePropertyChanged("wMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wSecond {
            get {
                return this.wSecondField;
            }
            set {
                if ((this.wSecondField.Equals(value) != true)) {
                    this.wSecondField = value;
                    this.RaisePropertyChanged("wSecond");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wYear {
            get {
                return this.wYearField;
            }
            set {
                if ((this.wYearField.Equals(value) != true)) {
                    this.wYearField = value;
                    this.RaisePropertyChanged("wYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.RemoteCommandInfoType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesRemoteCommandInfoType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] dValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint dwCmdCompleteSidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint dwCmdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] sValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] dValue {
            get {
                return this.dValueField;
            }
            set {
                if ((object.ReferenceEquals(this.dValueField, value) != true)) {
                    this.dValueField = value;
                    this.RaisePropertyChanged("dValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint dwCmdCompleteSid {
            get {
                return this.dwCmdCompleteSidField;
            }
            set {
                if ((this.dwCmdCompleteSidField.Equals(value) != true)) {
                    this.dwCmdCompleteSidField = value;
                    this.RaisePropertyChanged("dwCmdCompleteSid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint dwCmdId {
            get {
                return this.dwCmdIdField;
            }
            set {
                if ((this.dwCmdIdField.Equals(value) != true)) {
                    this.dwCmdIdField = value;
                    this.RaisePropertyChanged("dwCmdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] sValue {
            get {
                return this.sValueField;
            }
            set {
                if ((object.ReferenceEquals(this.sValueField, value) != true)) {
                    this.sValueField = value;
                    this.RaisePropertyChanged("sValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.BulkMachinePosType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesBulkMachinePosType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] dMachinePositionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] dMachinePosition {
            get {
                return this.dMachinePositionField;
            }
            set {
                if ((object.ReferenceEquals(this.dMachinePositionField, value) != true)) {
                    this.dMachinePositionField = value;
                    this.RaisePropertyChanged("dMachinePosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.BulkToolDataType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesBulkToolDataType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToolNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] tooldataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tooldatalengthField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ack {
            get {
                return this.AckField;
            }
            set {
                if ((object.ReferenceEquals(this.AckField, value) != true)) {
                    this.AckField = value;
                    this.RaisePropertyChanged("Ack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToolNumber {
            get {
                return this.ToolNumberField;
            }
            set {
                if ((this.ToolNumberField.Equals(value) != true)) {
                    this.ToolNumberField = value;
                    this.RaisePropertyChanged("ToolNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] tooldata {
            get {
                return this.tooldataField;
            }
            set {
                if ((object.ReferenceEquals(this.tooldataField, value) != true)) {
                    this.tooldataField = value;
                    this.RaisePropertyChanged("tooldata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tooldatalength {
            get {
                return this.tooldatalengthField;
            }
            set {
                if ((this.tooldatalengthField.Equals(value) != true)) {
                    this.tooldatalengthField = value;
                    this.RaisePropertyChanged("tooldatalength");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.BulkCurrentPartSetupType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesBulkCurrentPartSetupType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] A_CenterlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] B_CenterlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] C_CenterlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double XYSkewAngleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkMachinePosType offsetsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] A_Centerline {
            get {
                return this.A_CenterlineField;
            }
            set {
                if ((object.ReferenceEquals(this.A_CenterlineField, value) != true)) {
                    this.A_CenterlineField = value;
                    this.RaisePropertyChanged("A_Centerline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] B_Centerline {
            get {
                return this.B_CenterlineField;
            }
            set {
                if ((object.ReferenceEquals(this.B_CenterlineField, value) != true)) {
                    this.B_CenterlineField = value;
                    this.RaisePropertyChanged("B_Centerline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] C_Centerline {
            get {
                return this.C_CenterlineField;
            }
            set {
                if ((object.ReferenceEquals(this.C_CenterlineField, value) != true)) {
                    this.C_CenterlineField = value;
                    this.RaisePropertyChanged("C_Centerline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double XYSkewAngle {
            get {
                return this.XYSkewAngleField;
            }
            set {
                if ((this.XYSkewAngleField.Equals(value) != true)) {
                    this.XYSkewAngleField = value;
                    this.RaisePropertyChanged("XYSkewAngle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.DataService.UnmanagedDataTypesBulkMachinePosType offsets {
            get {
                return this.offsetsField;
            }
            set {
                if ((this.offsetsField.Equals(value) != true)) {
                    this.offsetsField = value;
                    this.RaisePropertyChanged("offsets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetBulkParams", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class SetBulkParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.DataService.BulkWrapper ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SID {
            get {
                return this.SIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SIDField, value) != true)) {
                    this.SIDField = value;
                    this.RaisePropertyChanged("SID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.DataService.BulkWrapper Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoteRapidMoveData", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class RemoteRapidMoveData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AAxisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AxisSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BAxisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CAxisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FeedRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OverrideOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartRelativeSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double UAxisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double XAxisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double YAxisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ZAxisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AAxis {
            get {
                return this.AAxisField;
            }
            set {
                if ((this.AAxisField.Equals(value) != true)) {
                    this.AAxisField = value;
                    this.RaisePropertyChanged("AAxis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AxisSet {
            get {
                return this.AxisSetField;
            }
            set {
                if ((this.AxisSetField.Equals(value) != true)) {
                    this.AxisSetField = value;
                    this.RaisePropertyChanged("AxisSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BAxis {
            get {
                return this.BAxisField;
            }
            set {
                if ((this.BAxisField.Equals(value) != true)) {
                    this.BAxisField = value;
                    this.RaisePropertyChanged("BAxis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CAxis {
            get {
                return this.CAxisField;
            }
            set {
                if ((this.CAxisField.Equals(value) != true)) {
                    this.CAxisField = value;
                    this.RaisePropertyChanged("CAxis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FeedRate {
            get {
                return this.FeedRateField;
            }
            set {
                if ((this.FeedRateField.Equals(value) != true)) {
                    this.FeedRateField = value;
                    this.RaisePropertyChanged("FeedRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OverrideOff {
            get {
                return this.OverrideOffField;
            }
            set {
                if ((this.OverrideOffField.Equals(value) != true)) {
                    this.OverrideOffField = value;
                    this.RaisePropertyChanged("OverrideOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartRelativeSystem {
            get {
                return this.PartRelativeSystemField;
            }
            set {
                if ((this.PartRelativeSystemField.Equals(value) != true)) {
                    this.PartRelativeSystemField = value;
                    this.RaisePropertyChanged("PartRelativeSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double UAxis {
            get {
                return this.UAxisField;
            }
            set {
                if ((this.UAxisField.Equals(value) != true)) {
                    this.UAxisField = value;
                    this.RaisePropertyChanged("UAxis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double XAxis {
            get {
                return this.XAxisField;
            }
            set {
                if ((this.XAxisField.Equals(value) != true)) {
                    this.XAxisField = value;
                    this.RaisePropertyChanged("XAxis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double YAxis {
            get {
                return this.YAxisField;
            }
            set {
                if ((this.YAxisField.Equals(value) != true)) {
                    this.YAxisField = value;
                    this.RaisePropertyChanged("YAxis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ZAxis {
            get {
                return this.ZAxisField;
            }
            set {
                if ((this.ZAxisField.Equals(value) != true)) {
                    this.ZAxisField = value;
                    this.RaisePropertyChanged("ZAxis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WirelessJogData", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class WirelessJogData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int axisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jogModeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jogTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jogWheelCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double overridePercentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int axis {
            get {
                return this.axisField;
            }
            set {
                if ((this.axisField.Equals(value) != true)) {
                    this.axisField = value;
                    this.RaisePropertyChanged("axis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jogModeType {
            get {
                return this.jogModeTypeField;
            }
            set {
                if ((this.jogModeTypeField.Equals(value) != true)) {
                    this.jogModeTypeField = value;
                    this.RaisePropertyChanged("jogModeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jogType {
            get {
                return this.jogTypeField;
            }
            set {
                if ((this.jogTypeField.Equals(value) != true)) {
                    this.jogTypeField = value;
                    this.RaisePropertyChanged("jogType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jogWheelCount {
            get {
                return this.jogWheelCountField;
            }
            set {
                if ((this.jogWheelCountField.Equals(value) != true)) {
                    this.jogWheelCountField = value;
                    this.RaisePropertyChanged("jogWheelCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double overridePercent {
            get {
                return this.overridePercentField;
            }
            set {
                if ((this.overridePercentField.Equals(value) != true)) {
                    this.overridePercentField = value;
                    this.RaisePropertyChanged("overridePercent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WcfDataServices", ConfigurationName="DataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetVersion", ReplyAction="WcfDataServices/IDataService/GetVersionResponse")]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetServerVersion", ReplyAction="WcfDataServices/IDataService/GetServerVersionResponse")]
        double GetServerVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetClock", ReplyAction="WcfDataServices/IDataService/GetClockResponse")]
        int GetClock();
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/SetSID", ReplyAction="WcfDataServices/IDataService/SetSIDResponse")]
        void SetSID(WinMaxDataServiceExample.DataService.SIDValue sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/SetIntSID", ReplyAction="WcfDataServices/IDataService/SetIntSIDResponse")]
        void SetIntSID(string SID, int sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/SetDoubleSID", ReplyAction="WcfDataServices/IDataService/SetDoubleSIDResponse")]
        void SetDoubleSID(string SID, double sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetSID", ReplyAction="WcfDataServices/IDataService/GetSIDResponse")]
        WinMaxDataServiceExample.DataService.SIDValue GetSID(string sidName);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetDoubleSID", ReplyAction="WcfDataServices/IDataService/GetDoubleSIDResponse")]
        double GetDoubleSID(string sidName);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetIntSID", ReplyAction="WcfDataServices/IDataService/GetIntSIDResponse")]
        int GetIntSID(string sidName);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetBulkByXML", ReplyAction="WcfDataServices/IDataService/GetBulkByXMLResponse")]
        System.Xml.XmlElement GetBulkByXML(string sidName);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetBulk", ReplyAction="WcfDataServices/IDataService/GetBulkResponse")]
        WinMaxDataServiceExample.DataService.BulkWrapper GetBulk(WinMaxDataServiceExample.DataService.GetBulkParams parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/SetBulk", ReplyAction="WcfDataServices/IDataService/SetBulkResponse")]
        void SetBulk(WinMaxDataServiceExample.DataService.SetBulkParams parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetChangedBulkByXML", ReplyAction="WcfDataServices/IDataService/GetChangedBulkByXMLResponse")]
        System.Xml.XmlElement GetChangedBulkByXML(WinMaxDataServiceExample.DataService.SIDValue sv);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/Subscribe", ReplyAction="WcfDataServices/IDataService/SubscribeResponse")]
        void Subscribe(string sidName);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/Unsubscribe", ReplyAction="WcfDataServices/IDataService/UnsubscribeResponse")]
        void Unsubscribe(string sidName);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetChangedSIDs", ReplyAction="WcfDataServices/IDataService/GetChangedSIDsResponse")]
        string GetChangedSIDs(string stringSIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetChangedSIDValues", ReplyAction="WcfDataServices/IDataService/GetChangedSIDValuesResponse")]
        WinMaxDataServiceExample.DataService.SIDValue[] GetChangedSIDValues(WinMaxDataServiceExample.DataService.SIDValue[] values);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/RemoteRapidMove", ReplyAction="WcfDataServices/IDataService/RemoteRapidMoveResponse")]
        bool RemoteRapidMove(WinMaxDataServiceExample.DataService.RemoteRapidMoveData rrmd);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/WirelessJog", ReplyAction="WcfDataServices/IDataService/WirelessJogResponse")]
        bool WirelessJog(WinMaxDataServiceExample.DataService.WirelessJogData wjd);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/ProcessCommandRequest", ReplyAction="WcfDataServices/IDataService/ProcessCommandRequestResponse")]
        void ProcessCommandRequest(double sbm);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/DownloadFile", ReplyAction="WcfDataServices/IDataService/DownloadFileResponse")]
        System.IO.Stream DownloadFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/GetCurrentGraphicsProgram", ReplyAction="WcfDataServices/IDataService/GetCurrentGraphicsProgramResponse")]
        System.IO.Stream GetCurrentGraphicsProgram();
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfDataServices/IDataService/StringToGID", ReplyAction="WcfDataServices/IDataService/StringToGIDResponse")]
        uint StringToGID(string SIDname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : WinMaxDataServiceExample.DataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<WinMaxDataServiceExample.DataService.IDataService>, WinMaxDataServiceExample.DataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public double GetServerVersion() {
            return base.Channel.GetServerVersion();
        }
        
        public int GetClock() {
            return base.Channel.GetClock();
        }
        
        public void SetSID(WinMaxDataServiceExample.DataService.SIDValue sv) {
            base.Channel.SetSID(sv);
        }
        
        public void SetIntSID(string SID, int sv) {
            base.Channel.SetIntSID(SID, sv);
        }
        
        public void SetDoubleSID(string SID, double sv) {
            base.Channel.SetDoubleSID(SID, sv);
        }
        
        public WinMaxDataServiceExample.DataService.SIDValue GetSID(string sidName) {
            return base.Channel.GetSID(sidName);
        }
        
        public double GetDoubleSID(string sidName) {
            return base.Channel.GetDoubleSID(sidName);
        }
        
        public int GetIntSID(string sidName) {
            return base.Channel.GetIntSID(sidName);
        }
        
        public System.Xml.XmlElement GetBulkByXML(string sidName) {
            return base.Channel.GetBulkByXML(sidName);
        }
        
        public WinMaxDataServiceExample.DataService.BulkWrapper GetBulk(WinMaxDataServiceExample.DataService.GetBulkParams parameters) {
            return base.Channel.GetBulk(parameters);
        }
        
        public void SetBulk(WinMaxDataServiceExample.DataService.SetBulkParams parameters) {
            base.Channel.SetBulk(parameters);
        }
        
        public System.Xml.XmlElement GetChangedBulkByXML(WinMaxDataServiceExample.DataService.SIDValue sv) {
            return base.Channel.GetChangedBulkByXML(sv);
        }
        
        public void Subscribe(string sidName) {
            base.Channel.Subscribe(sidName);
        }
        
        public void Unsubscribe(string sidName) {
            base.Channel.Unsubscribe(sidName);
        }
        
        public string GetChangedSIDs(string stringSIDs) {
            return base.Channel.GetChangedSIDs(stringSIDs);
        }
        
        public WinMaxDataServiceExample.DataService.SIDValue[] GetChangedSIDValues(WinMaxDataServiceExample.DataService.SIDValue[] values) {
            return base.Channel.GetChangedSIDValues(values);
        }
        
        public bool RemoteRapidMove(WinMaxDataServiceExample.DataService.RemoteRapidMoveData rrmd) {
            return base.Channel.RemoteRapidMove(rrmd);
        }
        
        public bool WirelessJog(WinMaxDataServiceExample.DataService.WirelessJogData wjd) {
            return base.Channel.WirelessJog(wjd);
        }
        
        public void ProcessCommandRequest(double sbm) {
            base.Channel.ProcessCommandRequest(sbm);
        }
        
        public System.IO.Stream DownloadFile(string fileName) {
            return base.Channel.DownloadFile(fileName);
        }
        
        public System.IO.Stream GetCurrentGraphicsProgram() {
            return base.Channel.GetCurrentGraphicsProgram();
        }
        
        public uint StringToGID(string SIDname) {
            return base.Channel.StringToGID(SIDname);
        }
    }
}
