//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMaxDataServiceExample.NotificationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SIDValue", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class SIDValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SID {
            get {
                return this.SIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SIDField, value) != true)) {
                    this.SIDField = value;
                    this.RaisePropertyChanged("SID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Since {
            get {
                return this.SinceField;
            }
            set {
                if ((this.SinceField.Equals(value) != true)) {
                    this.SinceField = value;
                    this.RaisePropertyChanged("Since");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBulkParams", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class GetBulkParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SID {
            get {
                return this.SIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SIDField, value) != true)) {
                    this.SIDField = value;
                    this.RaisePropertyChanged("SID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkWrapper", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.NotificationService.Bulk bulkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.NotificationService.Bulk bulk {
            get {
                return this.bulkField;
            }
            set {
                if ((object.ReferenceEquals(this.bulkField, value) != true)) {
                    this.bulkField = value;
                    this.RaisePropertyChanged("bulk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bulk", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.NotificationService.BulkToolChangeInfoTypeBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.NotificationService.BulkNotificationDataTypeBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.NotificationService.BulkRemoteCommandDataTypeBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.NotificationService.BulkMachinePosTypeBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.NotificationService.BulkToolDataTypeBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinMaxDataServiceExample.NotificationService.BulkPartSetupTypeBox))]
    public partial class Bulk : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkToolChangeInfoTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkToolChangeInfoTypeBox : WinMaxDataServiceExample.NotificationService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkToolChangeInfoType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkToolChangeInfoType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkNotificationDataTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkNotificationDataTypeBox : WinMaxDataServiceExample.NotificationService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkNotificationDataType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkNotificationDataType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkRemoteCommandDataTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkRemoteCommandDataTypeBox : WinMaxDataServiceExample.NotificationService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesRemoteCommandInfoType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesRemoteCommandInfoType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkMachinePosTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkMachinePosTypeBox : WinMaxDataServiceExample.NotificationService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkMachinePosType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkMachinePosType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkToolDataTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkToolDataTypeBox : WinMaxDataServiceExample.NotificationService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkToolDataType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkToolDataType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkPartSetupTypeBox", Namespace="WcfDataServices")]
    [System.SerializableAttribute()]
    public partial class BulkPartSetupTypeBox : WinMaxDataServiceExample.NotificationService.Bulk {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkCurrentPartSetupType BulkStructField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkCurrentPartSetupType BulkStruct {
            get {
                return this.BulkStructField;
            }
            set {
                if ((this.BulkStructField.Equals(value) != true)) {
                    this.BulkStructField = value;
                    this.RaisePropertyChanged("BulkStruct");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.BulkToolChangeInfoType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesBulkToolChangeInfoType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bAutoSafetyCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bAutoToolChangeCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bManualSafetyCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bManualToolChangeCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bMoveToZone1CouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bMoveToZone2CouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bPalletChangeCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bTPSInsertToolCouldMoveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] bTPSRemoveToolCouldMoveField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bAutoSafetyCouldMove {
            get {
                return this.bAutoSafetyCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bAutoSafetyCouldMoveField, value) != true)) {
                    this.bAutoSafetyCouldMoveField = value;
                    this.RaisePropertyChanged("bAutoSafetyCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bAutoToolChangeCouldMove {
            get {
                return this.bAutoToolChangeCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bAutoToolChangeCouldMoveField, value) != true)) {
                    this.bAutoToolChangeCouldMoveField = value;
                    this.RaisePropertyChanged("bAutoToolChangeCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bManualSafetyCouldMove {
            get {
                return this.bManualSafetyCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bManualSafetyCouldMoveField, value) != true)) {
                    this.bManualSafetyCouldMoveField = value;
                    this.RaisePropertyChanged("bManualSafetyCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bManualToolChangeCouldMove {
            get {
                return this.bManualToolChangeCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bManualToolChangeCouldMoveField, value) != true)) {
                    this.bManualToolChangeCouldMoveField = value;
                    this.RaisePropertyChanged("bManualToolChangeCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bMoveToZone1CouldMove {
            get {
                return this.bMoveToZone1CouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bMoveToZone1CouldMoveField, value) != true)) {
                    this.bMoveToZone1CouldMoveField = value;
                    this.RaisePropertyChanged("bMoveToZone1CouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bMoveToZone2CouldMove {
            get {
                return this.bMoveToZone2CouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bMoveToZone2CouldMoveField, value) != true)) {
                    this.bMoveToZone2CouldMoveField = value;
                    this.RaisePropertyChanged("bMoveToZone2CouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bPalletChangeCouldMove {
            get {
                return this.bPalletChangeCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bPalletChangeCouldMoveField, value) != true)) {
                    this.bPalletChangeCouldMoveField = value;
                    this.RaisePropertyChanged("bPalletChangeCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bTPSInsertToolCouldMove {
            get {
                return this.bTPSInsertToolCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bTPSInsertToolCouldMoveField, value) != true)) {
                    this.bTPSInsertToolCouldMoveField = value;
                    this.RaisePropertyChanged("bTPSInsertToolCouldMove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] bTPSRemoveToolCouldMove {
            get {
                return this.bTPSRemoveToolCouldMoveField;
            }
            set {
                if ((object.ReferenceEquals(this.bTPSRemoveToolCouldMoveField, value) != true)) {
                    this.bTPSRemoveToolCouldMoveField = value;
                    this.RaisePropertyChanged("bTPSRemoveToolCouldMove");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.BulkNotificationDataType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesBulkNotificationDataType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] m_MsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int m_MsgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort m_NotificationIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.NotificationService.UnmanagedDataTypes_SYSTEMTIME m_TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] m_wrcFileNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] m_Msg {
            get {
                return this.m_MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.m_MsgField, value) != true)) {
                    this.m_MsgField = value;
                    this.RaisePropertyChanged("m_Msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int m_MsgType {
            get {
                return this.m_MsgTypeField;
            }
            set {
                if ((this.m_MsgTypeField.Equals(value) != true)) {
                    this.m_MsgTypeField = value;
                    this.RaisePropertyChanged("m_MsgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort m_NotificationIndex {
            get {
                return this.m_NotificationIndexField;
            }
            set {
                if ((this.m_NotificationIndexField.Equals(value) != true)) {
                    this.m_NotificationIndexField = value;
                    this.RaisePropertyChanged("m_NotificationIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.NotificationService.UnmanagedDataTypes_SYSTEMTIME m_Timestamp {
            get {
                return this.m_TimestampField;
            }
            set {
                if ((this.m_TimestampField.Equals(value) != true)) {
                    this.m_TimestampField = value;
                    this.RaisePropertyChanged("m_Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] m_wrcFileName {
            get {
                return this.m_wrcFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.m_wrcFileNameField, value) != true)) {
                    this.m_wrcFileNameField = value;
                    this.RaisePropertyChanged("m_wrcFileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes._SYSTEMTIME", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypes_SYSTEMTIME : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wDayOfWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wMillisecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wMinuteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wSecondField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort wYearField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wDay {
            get {
                return this.wDayField;
            }
            set {
                if ((this.wDayField.Equals(value) != true)) {
                    this.wDayField = value;
                    this.RaisePropertyChanged("wDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wDayOfWeek {
            get {
                return this.wDayOfWeekField;
            }
            set {
                if ((this.wDayOfWeekField.Equals(value) != true)) {
                    this.wDayOfWeekField = value;
                    this.RaisePropertyChanged("wDayOfWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wHour {
            get {
                return this.wHourField;
            }
            set {
                if ((this.wHourField.Equals(value) != true)) {
                    this.wHourField = value;
                    this.RaisePropertyChanged("wHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wMilliseconds {
            get {
                return this.wMillisecondsField;
            }
            set {
                if ((this.wMillisecondsField.Equals(value) != true)) {
                    this.wMillisecondsField = value;
                    this.RaisePropertyChanged("wMilliseconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wMinute {
            get {
                return this.wMinuteField;
            }
            set {
                if ((this.wMinuteField.Equals(value) != true)) {
                    this.wMinuteField = value;
                    this.RaisePropertyChanged("wMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wMonth {
            get {
                return this.wMonthField;
            }
            set {
                if ((this.wMonthField.Equals(value) != true)) {
                    this.wMonthField = value;
                    this.RaisePropertyChanged("wMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wSecond {
            get {
                return this.wSecondField;
            }
            set {
                if ((this.wSecondField.Equals(value) != true)) {
                    this.wSecondField = value;
                    this.RaisePropertyChanged("wSecond");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort wYear {
            get {
                return this.wYearField;
            }
            set {
                if ((this.wYearField.Equals(value) != true)) {
                    this.wYearField = value;
                    this.RaisePropertyChanged("wYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.RemoteCommandInfoType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesRemoteCommandInfoType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] dValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint dwCmdCompleteSidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint dwCmdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] sValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] dValue {
            get {
                return this.dValueField;
            }
            set {
                if ((object.ReferenceEquals(this.dValueField, value) != true)) {
                    this.dValueField = value;
                    this.RaisePropertyChanged("dValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint dwCmdCompleteSid {
            get {
                return this.dwCmdCompleteSidField;
            }
            set {
                if ((this.dwCmdCompleteSidField.Equals(value) != true)) {
                    this.dwCmdCompleteSidField = value;
                    this.RaisePropertyChanged("dwCmdCompleteSid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint dwCmdId {
            get {
                return this.dwCmdIdField;
            }
            set {
                if ((this.dwCmdIdField.Equals(value) != true)) {
                    this.dwCmdIdField = value;
                    this.RaisePropertyChanged("dwCmdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] sValue {
            get {
                return this.sValueField;
            }
            set {
                if ((object.ReferenceEquals(this.sValueField, value) != true)) {
                    this.sValueField = value;
                    this.RaisePropertyChanged("sValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.BulkMachinePosType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesBulkMachinePosType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] dMachinePositionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] dMachinePosition {
            get {
                return this.dMachinePositionField;
            }
            set {
                if ((object.ReferenceEquals(this.dMachinePositionField, value) != true)) {
                    this.dMachinePositionField = value;
                    this.RaisePropertyChanged("dMachinePosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.BulkToolDataType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesBulkToolDataType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToolNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] tooldataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tooldatalengthField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ack {
            get {
                return this.AckField;
            }
            set {
                if ((object.ReferenceEquals(this.AckField, value) != true)) {
                    this.AckField = value;
                    this.RaisePropertyChanged("Ack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToolNumber {
            get {
                return this.ToolNumberField;
            }
            set {
                if ((this.ToolNumberField.Equals(value) != true)) {
                    this.ToolNumberField = value;
                    this.RaisePropertyChanged("ToolNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] tooldata {
            get {
                return this.tooldataField;
            }
            set {
                if ((object.ReferenceEquals(this.tooldataField, value) != true)) {
                    this.tooldataField = value;
                    this.RaisePropertyChanged("tooldata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tooldatalength {
            get {
                return this.tooldatalengthField;
            }
            set {
                if ((this.tooldatalengthField.Equals(value) != true)) {
                    this.tooldatalengthField = value;
                    this.RaisePropertyChanged("tooldatalength");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnmanagedDataTypes.BulkCurrentPartSetupType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServices")]
    [System.SerializableAttribute()]
    public partial struct UnmanagedDataTypesBulkCurrentPartSetupType : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] A_CenterlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] B_CenterlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] C_CenterlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double XYSkewAngleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkMachinePosType offsetsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] A_Centerline {
            get {
                return this.A_CenterlineField;
            }
            set {
                if ((object.ReferenceEquals(this.A_CenterlineField, value) != true)) {
                    this.A_CenterlineField = value;
                    this.RaisePropertyChanged("A_Centerline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] B_Centerline {
            get {
                return this.B_CenterlineField;
            }
            set {
                if ((object.ReferenceEquals(this.B_CenterlineField, value) != true)) {
                    this.B_CenterlineField = value;
                    this.RaisePropertyChanged("B_Centerline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] C_Centerline {
            get {
                return this.C_CenterlineField;
            }
            set {
                if ((object.ReferenceEquals(this.C_CenterlineField, value) != true)) {
                    this.C_CenterlineField = value;
                    this.RaisePropertyChanged("C_Centerline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double XYSkewAngle {
            get {
                return this.XYSkewAngleField;
            }
            set {
                if ((this.XYSkewAngleField.Equals(value) != true)) {
                    this.XYSkewAngleField = value;
                    this.RaisePropertyChanged("XYSkewAngle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WinMaxDataServiceExample.NotificationService.UnmanagedDataTypesBulkMachinePosType offsets {
            get {
                return this.offsetsField;
            }
            set {
                if ((this.offsetsField.Equals(value) != true)) {
                    this.offsetsField = value;
                    this.RaisePropertyChanged("offsets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.hurco.com/2013/05", ConfigurationName="NotificationService.INotificationService", CallbackContract=typeof(WinMaxDataServiceExample.NotificationService.INotificationServiceCallback))]
    public interface INotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hurco.com/2013/05/INotificationService/Subscribe", ReplyAction="http://www.hurco.com/2013/05/INotificationService/SubscribeResponse")]
        void Subscribe(string sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hurco.com/2013/05/INotificationService/Unsubscribe", ReplyAction="http://www.hurco.com/2013/05/INotificationService/UnsubscribeResponse")]
        void Unsubscribe(string sid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hurco.com/2013/05/INotificationService/BeginSubscribe", ReplyAction="http://www.hurco.com/2013/05/INotificationService/BeginSubscribeResponse")]
        void BeginSubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hurco.com/2013/05/INotificationService/EndSubscribe", ReplyAction="http://www.hurco.com/2013/05/INotificationService/EndSubscribeResponse")]
        void EndSubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hurco.com/2013/05/INotificationService/GetSID", ReplyAction="http://www.hurco.com/2013/05/INotificationService/GetSIDResponse")]
        WinMaxDataServiceExample.NotificationService.SIDValue GetSID(string sidName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hurco.com/2013/05/INotificationService/GetDoubleSID", ReplyAction="http://www.hurco.com/2013/05/INotificationService/GetDoubleSIDResponse")]
        double GetDoubleSID(string sidName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hurco.com/2013/05/INotificationService/GetIntSID", ReplyAction="http://www.hurco.com/2013/05/INotificationService/GetIntSIDResponse")]
        int GetIntSID(string sidName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hurco.com/2013/05/INotificationService/GetBulk", ReplyAction="http://www.hurco.com/2013/05/INotificationService/GetBulkResponse")]
        WinMaxDataServiceExample.NotificationService.BulkWrapper GetBulk(WinMaxDataServiceExample.NotificationService.GetBulkParams parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.hurco.com/2013/05/INotificationService/Notify")]
        void Notify(string sid, string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationServiceChannel : WinMaxDataServiceExample.NotificationService.INotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationServiceClient : System.ServiceModel.DuplexClientBase<WinMaxDataServiceExample.NotificationService.INotificationService>, WinMaxDataServiceExample.NotificationService.INotificationService {
        
        public NotificationServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public NotificationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public NotificationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe(string sid) {
            base.Channel.Subscribe(sid);
        }
        
        public void Unsubscribe(string sid) {
            base.Channel.Unsubscribe(sid);
        }
        
        public void BeginSubscribe() {
            base.Channel.BeginSubscribe();
        }
        
        public void EndSubscribe() {
            base.Channel.EndSubscribe();
        }
        
        public WinMaxDataServiceExample.NotificationService.SIDValue GetSID(string sidName) {
            return base.Channel.GetSID(sidName);
        }
        
        public double GetDoubleSID(string sidName) {
            return base.Channel.GetDoubleSID(sidName);
        }
        
        public int GetIntSID(string sidName) {
            return base.Channel.GetIntSID(sidName);
        }
        
        public WinMaxDataServiceExample.NotificationService.BulkWrapper GetBulk(WinMaxDataServiceExample.NotificationService.GetBulkParams parameters) {
            return base.Channel.GetBulk(parameters);
        }
    }
}
